USE [pos101.priorpos.com]
GO

/****** Object:  Table [dbo].[UserWiseComponent]    Script Date: 10/30/2023 4:41:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserWiseComponent](
	[AutoId] [int] IDENTITY(1,1) NOT NULL,
	[UserAutoId] [int] NOT NULL,
	[ComponentAutoId] [int] NOT NULL,
 CONSTRAINT [PK_UserWiseComponent] PRIMARY KEY CLUSTERED 
(
	[AutoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


